### ISSUE TITLE
/dev/fb1

### ISSUE THREAD

**Issue by martinohanlon** [noisegate/fbpy#5]
I am using a TFT screen which appears as fb1. Is there a way to use /dev/fb1 rather than /dev/fb0? Thanks

**Comment by noisegate** [comment]
you could try changing /dev/fb0 into /dev/fb1 in:
https://github.com/noisegate/fbpy/blob/master/fbpy/utils/fbutils.c#L113

and recompile

**Comment by martinohanlon** [comment]
Thanks for the insight
